version: 0.1


ddpg: &DEFAULT
  state_dim: 21
  action_dim: 7
  max_action: 1.0
  discount: 0.99
  tau: 0.005
  expl_noise: 0.1
  actor_lr: !!float 3e-4
  critic_lr: !!float 3e-4
  actor:
    fc1: 256
    fc2: 128
    fc3: 32
    layer_norm: !!float 1e-12
  critic:
    fc1: 128
    fc2: 64
    fc3: 1
    layer_norm: !!float 1e-12
td3:
  <<: *DEFAULT
  policy_noise: 0.2
  noise_clip: 0.5
  policy_freq: 2
